version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user
hooks:
 AfterInstall:
    - location: fix_previleges.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: server_stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: server_start.sh
      timeout: 20
      runas: root
  
